CATALOGUE_HOST: catalogue.backend-{{ env }}.satyology.site
USER_HOST: user.backend-{{ env }}.satyology.site
CART_HOST: cart.backend-{{ env }}.satyology.site
SHIPPING_HOST: shipping.backend-{{ env }}.satyology.site
PAYMENT_HOST: payment.backend-{{ env }}.satyology.site
