[mongodb]
mongodb.satyology.site

[catalogue]
catalogue.satyology.site

[cart]
cart.satyology.site

[user]
user.satyology.site

[shipping]
shipping.satyology.site

[payment]
payment.satyology.site

[redis]
redis.satyology.site

[mysql]
mysql.satyology.site

[rabbitmq]
rabbitmq.satyology.site

[frontend]
satyology.site

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321

[localhost]
localhost