REDIS_HOST: redis-{{ env }}.satyology.site
CATALOGUE_HOST: catalogue.backend-{{ env }}.satyology.site # cart call catalogue via load balancer
CATALOGUE_PORT: 80 # cart call catalogue via load balancer so we used 80 instaed of 8080
