- name: Disable current nginx module
  ansible.builtin.command: dnf module disable nginx -y

- name: Enable required nginx module
  ansible.builtin.command: dnf module enable nginx:1.24 -y

- name: Installing nginx module
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: Starting and enabling frontend service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: Removing the default content that web server is serving
  ansible.builtin.shell: rm -rf /usr/share/nginx/html/*

- name: Download application code
  ansible.builtin.get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
    dest: /tmp/frontend.zip

- name: Unziping the code
  ansible.builtin.unarchive:
    src: /tmp/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: true

- name: Copying nginx conf file
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: Restart nginx
