MYSQL_ROOT_PASSWORD: "{{ lookup('amazon.aws.aws_ssm', '/roboshop/dev/mysql/mysql-root-password', region='us-east-1', decrypt=True) }}"
# THIS MYSQL ROOT PASSWORD IS STORED IN AWS SSM PARAMETER STORE securestring as option!!
